### ISSUE TITLE
tracer, #error{ code } & memoize

### ISSUE THREAD

**Issue by johnwebner** [otac0n/Pegasus#114]
First of all thank you for developing Pegasus.
I have some questions.

- How to use the tracer? What is the use case for it?

- `#error{ code } `: 
I tried to get the line and the column of the error.
Console.WriteLine(ex.Data["cursor"].Line);
=> No definition for _Line_
- -memoize:
Is there any rule of thumb when to use **memoize**?

**Comment by otac0n** [comment]
The tracer is used anytime you need to be able to perform some external action each time a rule is entered/exited.  Right now, there are two implementations of the `ITracer` interface: `DiagnosticsTracer`, which outputs the rule entry/exit events etc. to diagnostics output for debugging purposes; and `PerformanceTracer` which is used to measure the time each rule takes to execute on average.

The `PerformanceTracer` is used in the Workbench (included in the NuGet package) to provide recommendations on memoization.  You can see the implementation in the [`WarningsPerformanceTracer`](https://github.com/otac0n/Pegasus/blob/develop/Pegasus.Workbench/Pipeline/TestParser.cs#L89).  You can either use the workbench to get recommendations or provide your own implementation.

To get access to the cursor inside of the code seciont, use the `state` variable instead of `ex.Data["cursor"]`.

**Comment by johnwebner** [comment]
I use state variable to get the cursor in #error{ code }.
But [State and Error Handling Expressions](https://github.com/otac0n/Pegasus/wiki/Syntax-Guide#state-and-error-handling-expressions) says:
Error #error{ code }: ...The exception that is thrown will also have the Data["cursor"] property set, so that the location of the error can be determined.
E.g. I did the following:
```
try
{
    Parser parser = new Parser();
    var result = parser.Parse(str);
}
catch (FormatException ex)
{
    Console.WriteLine(ex.Message);
    Console.WriteLine(ex.Data["cursor"].Line);
}
```
and got: No definition for Line
Where and how to use `Data["cursor"]`?

**Comment by otac0n** [comment]
Here's how the Workbench does it:

https://github.com/otac0n/Pegasus/blob/develop/Pegasus.Workbench/Pipeline/PegParser.cs#L56
