### ISSUE TITLE
VS 2017 Intellisense and Resharper

### ISSUE THREAD

**Issue by chrismasters** [otac0n/Pegasus#115]
When I include a grammar and compile my project it generates code into obj/Debug fine and compiles, but then I get no Intellisense on the parser class, so I see false errors. Is this by design? If the code was output to the project directory and the file was included then everything would work fine, but as it stands I lose intellisense when the output is generated to the obj/Debug folder

I looked at bit more into this and I believe its Resharper causing the issue because it doesn't see the obj folder source as part of the project. Disabling resharper removes the errors but unfortunately it would be nice to be able to use Resharper completion with the generated code. Has anyone solved this?

**Comment by otac0n** [comment]
Pegasus adds the file paths to the MsBuild <Compile> collection pretty early in the build pipeline, you can see where we register the build actions here:
https://github.com/otac0n/Pegasus/blob/develop/Package/Pegasus.targets

```
  <PropertyGroup>
    <CompileDependsOn>$(CompileDependsOn);CompilePegGrammars</CompileDependsOn>
    <CoreCompileDependsOn>$(CoreCompileDependsOn);CompilePegGrammars</CoreCompileDependsOn>
    <BuildDependsOn>$(BuildDependsOn);CompilePegGrammars</BuildDependsOn>
    <CoreBuildDependsOn>$(CoreBuildDependsOn);CompilePegGrammars</CoreBuildDependsOn>
    <CleanDependsOn>$(CleanDependsOn);CleanPegGrammars</CleanDependsOn>
  </PropertyGroup>
```

Ultimately, you can put the files wherever you want by using a different MsBuild command.

```
  <Target Name="_CompilePegGrammars" DependsOnTargets="_UpdatePegGrammarsMetatdata" Inputs="$(MSBuildThisFileFullPath);$(MSBuildProjectFile);@(PegGrammar)" Outputs="@(PegGrammar -> '%(OutputPath)')">
    <CompilePegGrammar InputFiles="@(PegGrammar -> '%(FullPath)')" OutputFiles="@(PegGrammar -> '%(OutputPath)')" />
    <Message Text="%(PegGrammar.Identity) -> %(PegGrammar.OutputPath)" />
  </Target>
```

In order to mitigate these sorts of issues going forward, I'll avoid overwriting the `OutputPath` property, so that you can specify that you would like to output to the project directory instead. For example:

```
<PegGrammar Include="MyGrammar.peg">
    <OutputPath>MyGrammar.peg.g.cs</OutputPath>
</PegGrammar>
```
