### ISSUE TITLE
Type inference for sequence

### ISSUE THREAD

**Issue by david-pfx** [otac0n/Pegasus#73]
Currently no type inference is performed for a sequence construct. Instead the entire sequence is lifted out as type string. This is mostly not a useful default.
The proposal is to allow a sequence to have parts of it labelled distinctively, and for those parts to be used automatically to determine the type and output of the sequence. For example

```
id = $:[a-z0-9]i [ \t];
idlist = '(' $:id $:(',' $:id)*);
```

The idea is simply that all the tokens labelled as `$` of type `T` are concatenated into an `IList<T>`. If any tokens are a different type it's an error. If a token is already an `IList<T>` it gets interpolated/flattened into the list.
You could get cute and define $1, $2 etc to reorder the tokens, but not really necessary.

**Comment by otac0n** [comment]
So, if a sequence has only a single `$`, that would be the returned expression for that sequence:

foo = n:name f:(_ "-" $:name)

Any following expressions would still be evaluated, but the result of the expression would come from the `$` variable.

I believe that the multiple `$` -> `IList<T>` is insoluble for now, because inferring `T` is largely impossible without rearchitecting on top of Roslyn.  For example:

    @using System;
    @using Foo = System.String;

    x = $:a $:b $:c

    a <string> = "a"

    b <String> = "b"

    c <Foo> = "c"

In this case, Pegasus would have 3 expressions, all with different types, and wouldn't know which to pass as the type argument to `IList<T>`.

I can already hear you say "Just take the first one," but that can't be done lightly.

**Comment by otac0n** [comment]
I suppose we could auto-tuple.

**Comment by davidandl** [comment]
First case I think yes. You might ask: but what about those spare variables? Variables are OK because you might want to use those for guards or invoking other code. Unused variables might trigger a warning.

Second case: my proposal was 
a) if there is just one $, that's the return type and value 
b) with more than one $ they must be the same type `T` or `IList<T>`, the return type is `IList<T>` and the value is a (preferably flattened) list of those values. Mismatched types as in your example are an error. I wouldn't try for auto-tuple.

I'm a big fan of type inference for saving typing and errors. The goal is a sensible way of handling simple sequences containing unused elements.

**Comment by davidandl** [comment]
I have been able to solve all my problems with the existing features, at the cost of some verbosity.
This is a minor enhancement to improve the appearance and robustness of the code.

**Comment by otac0n** [comment]
(In repsponse to the original comment) The default is there mostly to provide easy implementation for terminal rules e.g.

    identifier = "" [a-z]+;

    integer <int> = s:("" [0-9]+) { int.Parse(s) }

    decimal <decimal> = s:([0-9]+ ("." [0-9]+)?) { int.Parse(s) }

So, I would argue that it does have a place in many grammars.

I like the idea of using `$` to mark the default return value of a sequence, so I'll leave this open for more discussion.

**Comment by otac0n** [comment]
I can't find a way to make this work, and this isn't blocking anything.  If you have any more suggestions on how to resolve the issues above, please reopen.
