### ISSUE TITLE
How do I install the VS extension that gives syntax highlighting and does it support VS 2017?

### ISSUE THREAD

**Issue by ejsmith** [otac0n/Pegasus#92]
Just wondering how I go about installing the extension to give me some syntax highlighting.

**Comment by otac0n** [comment]
The latest release of the extension can be downloaded from the [Visual Studio Gallery](https://visualstudiogallery.msdn.microsoft.com/650f1a68-6a3d-4608-90f9-2f5cec336fb1)

You can get the most recent prerelease version from the [AppVeyor](https://ci.appveyor.com/project/otac0n/pegasus/build/artifacts) build.  Although, at the time of writing, this is the exact same version as the visual studio gallery.

It currently doesn't support VS2017, but it may be just as simple as updating the manifest.  I'm open to contributions. :)

John

**Comment by ejsmith** [comment]
Ok, thanks for the response. I will try and find some time to get the extension updated for VS2017.

**Comment by attilah** [comment]
I decompressed the VSIX, modified the manifest, rezipped it and installed. Beside the VS warning it works.

My bigger problem with the project is that it cannot be build with VS2017 after 1 way project migration.

If @otac0n agrees, we should refactor the projects a bit, having the followings:
- Pegasus.Common (can be named otherwise, Pegasus.Core?), which is the shared and runtime part, can be .Net Standard 1.x (as low as possible)
- Pegasus.ParserGenerator (move out bits from the console app, also .Net Standard library
- Pegasus.MSBuild msbuild only stuff
- Pegasus.VisualStudio vs only stuff

If @otac0n and building in VS2015 or lower is not a requirement, we can move safely to the new tooling, if that's still a requirement, we can have separate csproj and sln files for that.

**Comment by ejsmith** [comment]
Yeah, this would be really nice. Really need to figure out how it will work with the new csproj system in .net core first though and that tooling isn't done yet.

**Comment by attilah** [comment]
The biggest "misconception" is attaching the new tooling to .Net Core. It is only connected to VS, but "connected" means that pre VS2017 will not support it. Since VS Community is a free product and if someone wants to compile any OSS project, then it cannot be a problem that "I've no license for that product" ;-)

[Orleans](http://github.com/dotnet/orleans) vNext is now built with new tooling and multitargeting without problems.

**Comment by otac0n** [comment]
Maintaining backwards compatibility of the build is not a huge concern.  AppVeyor would need to support it.

**Comment by otac0n** [comment]
The package has been updated to support VS2017.
